[package]
name = "puzzle-16"
version = "0.1.0"
authors = ["Chris Butler <chrisbutler296@gmail.com>"]
edition = "2018"

[dependencies]
failure = "*"
lazy_static = "*"
regex = "1"

[[bin]]
name = "puzzle-16"
