[package]
name = "puzzle-07"
version = "0.1.0"
authors = ["Chris Butler <chrisbutler296@gmail.com>"]
edition = "2018"

[dependencies]
failure = "*"
strsim = "*"
itertools = "*"
regex = "1"
lazy_static = "*"
