[package]
name = "puzzle-06"
version = "0.1.0"
authors = ["Chris Butler <chrisbutler296@gmail.com>"]
edition = "2018"

[dependencies]
failure     = "*"
itertools   = "*"
lazy_static = "*"
regex       = "1"
strsim      = "*"
